import he from "he"
import axios from "axios"
import { find } from "lodash"
import striptags from "striptags"

interface CaptionTrack {
  baseUrl: string
  vssId: string
  name: {
    simpleText: string
  }
  languageCode: string
  kind: string
}

const fetchData =
  typeof fetch === "function"
    ? async function fetchData(url: string) {
        const response = await fetch(url)
        return await response.text()
      }
    : async function fetchData(url: string) {
        const { data } = await axios.get(url)
        return data
      }

export interface SubtitleEntry {
  start: string
  dur: string
  text: string
}

export async function getSubtitles({ videoID, lang = "en" }: { videoID: string; lang: "en" | "de" | "fr" | string }): Promise<SubtitleEntry[]> {
  const data = await fetchData(`https://youtube.com/watch?v=${videoID}`)

  // * ensure we have access to captions data
  if (!data.includes("captionTracks")) throw new Error(`Could not find captions for video: ${videoID}`)

  const regex = /"captionTracks":(\[.*?\])/
  const match = regex.exec(data)

  if (!match) {
    throw new Error("Failed to parse caption tracks from video data")
  }

  const { captionTracks } = JSON.parse(`{${match[0]}}`) as { captionTracks: CaptionTrack[] }
  const subtitle =
    find(captionTracks, {
      vssId: `.${lang}`,
    }) ||
    find(captionTracks, {
      vssId: `a.${lang}`,
    }) ||
    find(captionTracks, ({ vssId }) => vssId && vssId.match(`.${lang}`))

  // * ensure we have found the correct subtitle lang
  if (!subtitle || !subtitle.baseUrl) throw new Error(`Could not find ${lang} captions for ${videoID}`)

  const transcript = await fetchData(subtitle.baseUrl)
  const lines = transcript
    .replace('<?xml version="1.0" encoding="utf-8" ?><transcript>', "")
    .replace("</transcript>", "")
    .split("</text>")
    .filter((line: string) => line && line.trim())
    .map((line: string) => {
      const startRegex = /start="([\d.]+)"/
      const durRegex = /dur="([\d.]+)"/

      const startMatch = startRegex.exec(line)
      const durMatch = durRegex.exec(line)

      if (!startMatch || !durMatch) {
        throw new Error("Failed to parse subtitle timing information")
      }

      const htmlText = line
        .replace(/<text.+>/, "")
        .replace(/&amp;/gi, "&")
        .replace(/<\/?[^>]+(>|$)/g, "")

      const decodedText = he.decode(htmlText)
      const text = striptags(decodedText)

      return {
        start: startMatch[1],
        dur: durMatch[1],
        text,
      }
    })

  return lines
}

export async function getAvailableSubtitles(videoID: string) {
  try {
    const data = await fetchData(`https://youtube.com/watch?v=${videoID}`)

    if (!data.includes("captionTracks")) throw new Error(`Could not find captions for video: ${videoID}`)

    const regex = /"captionTracks":(\[.*?\])/
    const match = regex.exec(data)

    if (!match) {
      throw new Error("Failed to parse caption tracks from video data")
    }

    const { captionTracks } = JSON.parse(`{${match[1]}}`) as { captionTracks: CaptionTrack[] }

    return captionTracks.map((track: CaptionTrack) => ({
      language: track.name.simpleText,
      languageCode: track.languageCode,
      name: track.name.simpleText,
      format: "vtt",
      isAutoGenerated: track.kind === "asr",
    }))
  } catch (error) {
    console.error("Error fetching available subtitles:", error)
    return []
  }
}
