import type { NextApiRequest, NextApiResponse } from 'next';
import { getAvailableSubtitles } from '../../../utils/subtitleFetcher';

type SubtitleTrack = {
  language: string;
  languageCode: string;
  name: string;
  format: string;
  isAutoGenerated: boolean;
};

type SubtitleResponse = {
  videoId: string;
  tracks: SubtitleTrack[];
  error?: string;
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<SubtitleResponse>
) {
  // Only allow GET requests
  if (req.method !== 'GET') {
    return res.status(405).json({ videoId: '', tracks: [], error: 'Method not allowed' });
  }

  try {
    const { videoId } = req.query;

    if (!videoId || typeof videoId !== 'string') {
      return res.status(400).json({ 
        videoId: '', 
        tracks: [], 
        error: 'A valid video ID is required' 
      });
    }

    const tracks = await getAvailableSubtitles(videoId);
    
    return res.status(200).json({
      videoId,
      tracks
    });
    
  } catch (error: any) {
    console.error('Error fetching subtitle tracks:', error);
    return res.status(500).json({ 
      videoId: req.query.videoId as string || '', 
      tracks: [], 
      error: error.message || 'Failed to fetch subtitle tracks' 
    });
  }
} 